name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Assure-toi de spécifier la version de Node.js que tu utilises

      - name: Installation des dépendances
        run: npm install  # Utilise npm ci si tu as un package-lock.json

      - name: Exécution des tests
        run: npm test
